#!/usr/bin/env python3
"""
build_editions.py — build the two editions of the Geography Keyword Builder
plugin from ONE shared source tree.

  Source : /home/ubuntu/LR-Geography-Builder.lrplugin/
  Output : /home/ubuntu/dist/
             Geography-Keyword-Builder.lrplugin          (END-USER edition)
             Geography-Keyword-Builder-Manager.lrplugin  (MANAGER edition)

Editions share the SAME source; they only differ in:
  • Edition.lua          → { isManager = true/false }
  • Info.lua             → name / toolkit identifier / LrPluginInfoProvider line
  • which files ship      → the end-user edition drops the GitHub / Wikidata
                            admin-only files (GitHubSettings, GitHubSync,
                            Base64, dkjson) and the verified/ JSON stubs.

Nothing in the country data (data/) is duplicated or diverged — both editions
carry the identical databases.
"""

import os
import re
import shutil

SRC = "/home/ubuntu/LR-Geography-Builder.lrplugin"
DIST = "/home/ubuntu/dist"

# Files/dirs the END-USER edition must NOT ship (Manager-only admin paths).
USER_EXCLUDE = {
    "GitHubSettings.lua",   # LrPluginInfoProvider (Plugin Manager GitHub UI) → 75s delay
    "GitHubSync.lua",       # GitHub REST client
    "Base64.lua",           # only used by GitHub push
    "dkjson.lua",           # only used by GitHub/Wikidata paths
    "verified",             # verified/ JSON stubs — manager-only
}

# Junk that should never be packaged.
def is_junk(name):
    return (
        name.startswith(".abacus")
        or name == ".DS_Store"
        or name.startswith("._")
        or name.endswith((".retcode", ".out", ".err"))
        or name in (".logs", ".git")
    )


def transform_info(text, *, is_manager):
    """Return Info.lua text adapted for the given edition."""
    if is_manager:
        # Manager: rename + new toolkit id + KEEP LrPluginInfoProvider.
        text = text.replace(
            'LrToolkitIdentifier = "com.lioddenMedia.geographyBuilder"',
            'LrToolkitIdentifier = "com.lioddenMedia.geographyBuilderManager"',
        )
        text = text.replace(
            'LrPluginName = "Geography Keyword Builder"',
            'LrPluginName = "Geography Keyword Builder \u2014 Manager"',
        )
        return text
    # End-user: keep original id + name (so existing installs upgrade in place),
    # but REMOVE the LrPluginInfoProvider line entirely (no Plugin Manager UI,
    # no ~75 s reload delay).
    out = []
    for line in text.split("\n"):
        if "LrPluginInfoProvider" in line:
            continue  # drop this line
        out.append(line)
    return "\n".join(out)


def copy_tree(dest, *, is_manager):
    if os.path.exists(dest):
        shutil.rmtree(dest)
    os.makedirs(dest)
    for entry in sorted(os.listdir(SRC)):
        if is_junk(entry):
            continue
        if (not is_manager) and entry in USER_EXCLUDE:
            continue
        s = os.path.join(SRC, entry)
        d = os.path.join(dest, entry)
        if os.path.isdir(s):
            shutil.copytree(
                s, d,
                ignore=lambda _dir, names: [n for n in names if is_junk(n)],
            )
        else:
            shutil.copy2(s, d)

    # Edition.lua
    with open(os.path.join(dest, "Edition.lua"), "w", encoding="utf-8") as fh:
        flag = "true" if is_manager else "false"
        fh.write(
            "-- Edition.lua — generated by build_editions.py. DO NOT edit by hand.\n"
            "return { isManager = %s }\n" % flag
        )

    # Info.lua transform
    info_path = os.path.join(dest, "Info.lua")
    with open(info_path, encoding="utf-8") as fh:
        info = fh.read()
    info = transform_info(info, is_manager=is_manager)
    with open(info_path, "w", encoding="utf-8") as fh:
        fh.write(info)


def main():
    os.makedirs(DIST, exist_ok=True)
    builds = [
        ("Geography-Keyword-Builder.lrplugin", False),          # end-user
        ("Geography-Keyword-Builder-Manager.lrplugin", True),   # manager
    ]
    for name, is_manager in builds:
        dest = os.path.join(DIST, name)
        copy_tree(dest, is_manager=is_manager)
        nfiles = sum(len(f) for _, _, f in os.walk(dest))
        print("built %-45s (%s edition, %d files)"
              % (name, "manager" if is_manager else "end-user", nfiles))


if __name__ == "__main__":
    main()
