-- Edition.lua — kept as a no-op placeholder.
--
-- IS_MANAGER is now controlled entirely by the prefs.manager_unlocked preference
-- (set via the password gate in Plugin Manager → Manager Access), NOT by this
-- file.  A single plugin binary therefore serves both regular users (locked) and
-- the plugin author (unlocked).
--
-- This file is preserved so that any install that still has the old Edition.lua-
-- reading block in ListVerification.lua will load this file harmlessly and get
-- isManager=false (end-user mode).  The block has been removed from v0.9.257+.
return { isManager = false }
