-- data/Botswana.lua
-- Auto-generated by build_9_countries.py  —  verify manually.
-- Source: GeoNames (CC BY 4.0) + curated lists.

return {

    meta = {
        version     = "0.1.0",
        country     = "Botswana",
        native_name = "Botswana",
        continent   = "Africa",
    },

    national_parks = {
            "Central Kalahari Game Reserve",
            "Chobe National Park",
            "Kgalagadi Transfrontier Park",
            "Khutse Game Reserve",
            "Makgadikgadi Pans National Park",
            "Moremi Game Reserve",
            "Nxai Pan National Park",
    },

    nature_reserves = {
            "Est de la reserve de Moremi region de Khwai",
            "Linyanti",
            "Nord de la reserve de Moremi",
            "Nord du parc national de Chobe riviere de Chobe",
            "Nxai Pan National Park",
            "Parc national de Nxai Pan",
            "Reserve de Kwedi nord du delta de l’Okavango",
            "Sud du parc national de Chobe region de Savute",
    },

    mountains = {
        { name = "Otse", elev = 1491, region = "" },
        { name = "Mabeleapodi Hill", elev = 1205, region = "Central District" },
        { name = "Sephikamolelo Hill", elev = 1203, region = "Central District" },
        { name = "Matuba", elev = 1167, region = "Central District" },
        { name = "Mount Aha", elev = 1153, region = "" },
        { name = "Machibaba Hill", elev = 1152, region = "Central District" },
        { name = "Sete Hill", elev = 1111, region = "Central District" },
        { name = "Phalachwe Hill", elev = 1100, region = "Central District" },
        { name = "Maifala Hills", elev = 1015, region = "Central District" },
    },

    lakes = {
            "Lake Xau",
            "Lake Ngami",
            "Gaborone Dam",
    },

    rivers = {
            "Shashe",
            "Xaudum",
            "Nosop",
            "Marico River",
            "Ramaquabane",
            "Okwa",
            "Dzivanini",
            "Ramatlabama",
            "Ngotwane",
            "Sebuyu Neyami",
            "Nata",
            "Tshokana",
            "Boteti",
            "Buitsivangor",
            "Eiseb",
            "Vukwi",
            "Taupye",
            "Serorome",
            "Ng-gokha",
            "Ncamasere",
            "Moloporivier",
            "Mhalatswe River",
            "Dikabeya",
            "Bonwapitse",
            "Kaua",
            "Groot Laagte",
            "Sebuyu N’Kulu",
            "Tutumi River",
            "Tsitlane",
            "Thamalakane River",
            "Tati River",
            "Taokhe",
            "Suka River",
            "Shua River",
            "Shuane River",
            "Mothwane",
            "Mokape",
            "Metsemotlhaba",
            "Marsupe River",
            "Makwegana Spillway",
            "Maitengwe",
            "Machous River",
            "Machokwane River",
            "Lyshuma",
            "Lotsane",
            "Kwala",
            "Kkhwapa",
            "Mashi",
            "Chobe",
            "Madikola",
            "Majeadinare",
            "Sikulane River",
            "Morupule",
            "Kuru",
            "Kopong",
            "Deka",
            "Lepashe River",
            "Mosope River",
            "Paje",
            "Robelela",
            "Mmanoko",
            "Serule",
            "Ghumandusha",
            "Tshakujuwo",
            "Taung",
            "Seswe",
            "Selepswe",
            "Savuti Channel",
            "Rooibock Laagte",
            "Rakabochwa",
            "Piwaning",
            "Pakwe",
            "Nghabe",
            "Ngamaseri",
            "Mourinuana",
            "Mosileme Laagte",
            "Moselebe",
            "Mombo",
            "Mokolane",
            "Mokhonong Laagte",
            "Mokhokhelo",
            "Mochaba",
            "Moanachira",
            "Mita",
            "Metsemaswaane",
            "Matsebe",
            "Matlhabanelo",
            "Marapong",
            "Manche",
            "Manasilonoko",
            "Malachane",
            "Makletsi Laagte",
            "Machooloata",
            "Lotlakani",
            "letiahau",
            "Kwikhai",
            "Kweneng Laagte",
            "Kudum",
            "Komu Dia Tsaba Laagte",
            "Kolobeng",
    },

    islands = {
            "Sidudu",
            "Kubu Island",
            "Gabasari Island",
            "Xgara Island",
            "Santantadibe Island",
            "Ngindi Island",
            "Namakha Island",
            "Motsaod Island",
            "Geune Kan Island",
            "Gechia Island",
            "Borokwe Island",
            "Bokwi Island",
            "Kai’kau Island",
            "Bobo Island",
            "Ai’Ao Island",
            "Ad’Ao Island",
            "Crocodile Island",
            "Delta de l’Okavango ile privee de Nxharaga",
            "Ile privee de Jao delta de l’Okavango",
            "Ile de Paradis delta de l’Okavango",
    },

    viewpoints = {
            "Okavango Delta viewpoint",
            "Makgadikgadi Pans viewpoint",
            "Tsodilo Hills viewpoint",
            "Otse Hill viewpoint",
    },

    counties = {
        {
            name = "Central District",
            municipalities = {
                {
                    name = "Bobonong",
                    primary_city = "Mmadinare",
                    cities = { "Mmadinare" },
                },
                {
                    name = "Lethlakane",
                    primary_city = "",
                    cities = {},
                },
                {
                    name = "Machaneng",
                    primary_city = "",
                    cities = {},
                },
                {
                    name = "Mahalapye",
                    primary_city = "",
                    cities = {},
                },
                {
                    name = "Palapye",
                    primary_city = "",
                    cities = {},
                },
                {
                    name = "Serowe",
                    primary_city = "Moijabana",
                    cities = { "Moijabana" },
                },
                {
                    name = "Tuli",
                    primary_city = "",
                    cities = {},
                },
                {
                    name = "Tutume",
                    primary_city = "",
                    cities = {},
                },
            },
        },
        {
            name = "Chobe District",
            municipalities = {
                {
                    name = "Chobe",
                    primary_city = "Kachikau",
                    cities = { "Kachikau", "Kavimba" },
                },
            },
        },
        {
            name = "City of Francistown",
            municipalities = {
                {
                    name = "City of Francistown",
                    primary_city = "Francistown",
                    cities = { "Francistown" },
                },
            },
        },
        {
            name = "Gaborone",
            municipalities = {
                {
                    name = "Gaborone",
                    primary_city = "Gaborone",
                    cities = { "Gaborone" },
                },
            },
        },
        {
            name = "Ghanzi District",
            municipalities = {
                {
                    name = "Ghanzi",
                    primary_city = "",
                    cities = {},
                },
            },
        },
        {
            name = "Jwaneng",
            municipalities = {
                {
                    name = "Jwaneng",
                    primary_city = "Jwaneng",
                    cities = { "Jwaneng" },
                },
            },
        },
        {
            name = "Kgalagadi District",
            municipalities = {
                {
                    name = "Gemsbok",
                    primary_city = "",
                    cities = {},
                },
                {
                    name = "Hukunsti",
                    primary_city = "Lehututu",
                    cities = { "Lehututu" },
                },
                {
                    name = "Tshabong",
                    primary_city = "",
                    cities = {},
                },
            },
        },
        {
            name = "Kgatleng District",
            municipalities = {
                {
                    name = "Kgatleng",
                    primary_city = "Pilane",
                    cities = { "Pilane" },
                },
            },
        },
        {
            name = "Kweneng District",
            municipalities = {
                {
                    name = "Kweneng North",
                    primary_city = "",
                    cities = {},
                },
                {
                    name = "Kweneng South",
                    primary_city = "",
                    cities = {},
                },
            },
        },
        {
            name = "Lobatse",
            municipalities = {
                {
                    name = "Lobatse",
                    primary_city = "Lobatse",
                    cities = { "Lobatse" },
                },
            },
        },
        {
            name = "North East District",
            municipalities = {
                {
                    name = "Masungu",
                    primary_city = "Sebina",
                    cities = { "Sebina", "Makaleng" },
                },
            },
        },
        {
            name = "North West District",
            municipalities = {
                {
                    name = "Ngamiland East",
                    primary_city = "",
                    cities = {},
                },
                {
                    name = "Ngamiland West",
                    primary_city = "Tsau",
                    cities = { "Tsau" },
                },
            },
        },
        {
            name = "Selibe Phikwe",
            municipalities = {
                {
                    name = "Selibe Phikwe",
                    primary_city = "Selebi-Phikwe",
                    cities = { "Selebi-Phikwe" },
                },
            },
        },
        {
            name = "South East District",
            municipalities = {
                {
                    name = "Ramotswa",
                    primary_city = "Ramotswa Station/Taung",
                    cities = { "Ramotswa Station/Taung" },
                },
                {
                    name = "South East",
                    primary_city = "",
                    cities = {},
                },
            },
        },
        {
            name = "Southern District",
            municipalities = {
                {
                    name = "Barolong",
                    primary_city = "",
                    cities = {},
                },
                {
                    name = "Ngwaketse Central",
                    primary_city = "Kgomokasitwa",
                    cities = { "Kgomokasitwa" },
                },
                {
                    name = "Ngwaketse North",
                    primary_city = "Pitseng",
                    cities = { "Pitseng" },
                },
                {
                    name = "Ngwaketse South",
                    primary_city = "Lorolwana",
                    cities = { "Lorolwana" },
                },
            },
        },
        {
            name = "Sowa Town",
            municipalities = {
                {
                    name = "Sowa Town",
                    primary_city = "Sowa",
                    cities = { "Sowa" },
                },
            },
        },
    },

}
