-- data/Russia.lua
-- Auto-generated by build_6_europe.py  —  verify manually.
-- Source: GeoNames (CC BY 4.0) + curated lists.

return {

    meta = {
        version     = "0.1.0",
        country     = "Russia",
        native_name = "Россия",
        continent   = "Europe",
    },

    national_parks = {
            "Curonian Spit National Park",
            "Kenozersky National Park",
            "Losiny Ostrov National Park",
            "Meshchyora National Park",
            "Pribaikalsky National Park",
            "Prielbrusye National Park",
            "Russian Arctic National Park",
            "Sochi National Park",
            "Tunkinsky National Park",
            "Valdaysky National Park",
            "Yugyd Va National Park",
            "Zabaykalsky National Park",
    },

    nature_reserves = {
            "Astrakhanskiy Zapovednik",
            "Baimo-Komissarovskaya Lesnaya Dacha",
            "Bairovskiy Zapovednik",
            "Bashkirskiy Zapovednik",
            "Bolshaya Kokshaga Nature Reserve",
            "Bureinskiy Zapovednik",
            "Dal’nevostochnyy Gosudarstvennyy Morskoy Zapovednik",
            "Darvinskiy Zapovednik",
            "Gosudarstvennyy Kompleks Zavidovo",
            "Gosudarstvennyy Prirodnyy Zapovednik Prisurskiy",
            "Gosudarstvennyy Zakaznik Stepnoy",
            "Gosudarstvennyy Zapovednik Bryanskiy Les",
            "Il’menskiy Gosudarstvennyy Zapovednik",
            "Kabardino-Balkarskiy Vysokognornyy Zapovednik",
            "Kandalakshskiy Zapovednik",
            "Khankayskiy Zakaznik",
            "Khopërskiy Zapovednik",
            "Lesopark Lesovodov Bashkirii",
            "Lesozashchitnaya Stantsiya Lespromkhoza Bashatinskogo",
            "Muromskiy Zakaznik",
            "Natsional’nyy Park Khvalynskiy",
            "Natsional’nyy Park Priel’brus’ye",
            "Nizhnekundryuchenskiy Zapovednik",
            "North Ossetia State Reserve",
            "Obzhorovskiy Uchastok Astrakhanskogo Zapovednika",
            "Pamyatnik Prirody Ptich’ya Gavan’",
            "Pechoro-Ilychskiy Zapovednik",
            "Pleshcheyevo Ozero National Park",
            "Prioksko-Terrasnyy Gosudarstvennyy Biosfernyy Zapovednik",
            "Pushkinskiy Zapovednik",
            "Rosa Khutor. Besedka (BCD) 1350",
            "Sayanskiy Zapovednik",
            "Sengileyevskiy Okhotnichiy Zakaznik",
            "Slëkminskiy Zapovednik",
            "Trëkhizbenskiy Uchastok Astrakhanskogo Zapovednika",
            "Tsentral’nolesnoy Zapovednik",
            "Tsentral’nosibirskiy Zapovednik",
            "Ussuriyskiy Zapovednik",
            "Verkhnetazovskiy Zapovednik",
            "Vitimskiy Zapovednik",
    },

    mountains = {
        { name = "Mount Elbrus", elev = 5642, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Dykhtau", elev = 5204, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Koshtantau", elev = 5152, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Katyntau", elev = 4780, region = "" },
        { name = "Gora Uilpata", elev = 4646, region = "North Ossetia" },
        { name = "Gora Saukhokh", elev = 4636, region = "North Ossetia" },
        { name = "Gora Kukurtli-Kolbashi", elev = 4624, region = "Karachayevo-Cherkesiya" },
        { name = "Gora Mailikhokh", elev = 4532, region = "North Ossetia" },
        { name = "Gora Ulluauzna", elev = 4527, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Salynngantau", elev = 4507, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Sugan", elev = 4489, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Tepli", elev = 4431, region = "North Ossetia" },
        { name = "Mta Chat’ini", elev = 4411, region = "" },
        { name = "Gora Tyutyubashi", elev = 4404, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Adyrsubashi", elev = 4349, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Gyul’chi", elev = 4293, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Bachakhi", elev = 4291, region = "" },
        { name = "Gora Dzhorashty", elev = 4278, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Dzhaylykbashi", elev = 4252, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Sullukolbashi", elev = 4251, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Kayaartybashi", elev = 4250, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Tyutyurgu", elev = 4237, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Lyal’ver", elev = 4197, region = "" },
        { name = "Gora Doppakh", elev = 4189, region = "" },
        { name = "Gora Shaurtu", elev = 4185, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Danosmta", elev = 4179, region = "Chechenskaya Respublika" },
        { name = "Gora Chegembashi", elev = 4157, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Orubashi", elev = 4152, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Addala-Shukhgel’meer", elev = 4151, region = "Dagestan" },
        { name = "Gora Tsukhgartykom", elev = 4149, region = "" },
        { name = "Gora Syrkhibarzond", elev = 4148, region = "North Ossetia" },
        { name = "Gora Shalbuzdag", elev = 4142, region = "Dagestan" },
        { name = "Gora Fytnargin", elev = 4134, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Yunomkaratau", elev = 4129, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Dyul’tydag", elev = 4127, region = "Dagestan" },
        { name = "Gora Kichkidar-Bashi", elev = 4122, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Kengchat", elev = 4122, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Tsmiakomkhokh", elev = 4117, region = "North Ossetia" },
        { name = "Gora Musostau", elev = 4110, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Bishiney-Dzhenolshob", elev = 4104, region = "Dagestan" },
        { name = "Gora Nakra", elev = 4078, region = "" },
        { name = "Gora Angobalameer", elev = 4076, region = "Dagestan" },
        { name = "Gora Taklik", elev = 4049, region = "Dagestan" },
        { name = "Gora Gokli", elev = 4046, region = "Dagestan" },
        { name = "Iriktschatbaschi", elev = 4046, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Kurmutau", elev = 4045, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Arkhon", elev = 4040, region = "North Ossetia" },
        { name = "Gora Tseyakhokh", elev = 4029, region = "North Ossetia" },
        { name = "Gora Latsga", elev = 4019, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Deavgay", elev = 4016, region = "Dagestan" },
        { name = "Gora Kezgenbashi", elev = 4013, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Sovietski Woin", elev = 4011, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Balial", elev = 4007, region = "Dagestan" },
        { name = "Gora Ruarnygish", elev = 3996, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Tsrik", elev = 3994, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Sakashilbashi", elev = 3993, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Tsunkalotameer", elev = 3981, region = "Dagestan" },
        { name = "Gora Khashkharva", elev = 3971, region = "Dagestan" },
        { name = "Subaschi", elev = 3968, region = "Kabardino-Balkarskaya Respublika" },
        { name = "Gora Balyksubashi", elev = 3932, region = "Kabardino-Balkarskaya Respublika" },
    },

    lakes = {
            "Lake Baikal",
            "Ozero Evoron",
            "Ozero Lebyazh’ye",
            "Lake Onega",
            "Langvatnet",
            "Ozero Bol’shoye Rogozero",
            "Ozero Bol’shoye Kizi",
            "Ozero Sudach’ye",
            "Ozero Seliger",
            "Ozero Ptich’ye",
            "Proletarskiy Vodokhranilishche",
            "Ozero Mastakh-Tysykachchi",
            "Ozero Shuoniyaur",
            "Ozero Shchigol’skoye",
            "Ozero Mal’skoye",
            "Lake Ladoga",
            "Ozero Këzenoyam",
            "Ozero Gimol’skoye",
            "Ozero El’milami",
            "Ozero Khindiktig-Khol’",
            "Ozero Taylakovskoye",
            "Ozero Selitryanoye",
            "Ozero Bol’shoye Toko",
            "Ozero Tunaycha",
            "Ozero Pesochnoye",
            "Ozero Vel’ye",
            "Vatskheryarvi",
            "Ozero Sel’gayarvi",
            "Ozero Gol’tsovoye",
            "Ozero Maloye Rogozero",
            "Ozero Kevyatozero",
            "Lake Yun Vudyavr",
            "Ozero Sobach’ye",
            "Ozero Noyan-Khol’",
            "Ozero Bol’shoye Yem’yakhovskoye",
            "Ozero Taymyr",
            "Ozero Malyy Mar-Kyuyël’",
            "Ozero Dzhënkyude",
            "Ozero Dal’zha",
            "Ozero Beloye",
            "Ozero Dolgoye",
            "Ozero Chërnoye",
            "Ozero Pyalozero",
            "Ozero Pukshazyarvi",
            "Ozero Puarent-Yarvi",
            "Ozero Pon’goma",
            "Piedsjaur",
            "Ozero Vernis-Yaur",
            "Ozero Nyasyukkyayarvi",
            "Ozero Nel’mozero",
            "Ozero Muy",
            "Ozero Loukhskoye",
            "Ozero Labdsh’yaur",
            "Ozero Kuets’yarvi",
            "Ozëra Kogchamalampi",
            "Ozero Khaykolya",
            "Ozero Konentyavr",
            "Ozero Bol’shoye Savino",
            "Ozero Berëzovoye",
            "Ozëra Baduk",
            "Ozero Uman’gozero",
            "Ozero Todzha",
            "Ozero Bol’shoye Yeravnoye",
            "Ozero Khorgi",
            "Ozero Suturuokha",
            "Ozero Pekul’neyskoye",
            "Ozero Bol’shoy Kalygir’",
            "Ozero Bol’shoye Vavayskoye",
            "Ozero Bol’shoye Chibisanskoye",
            "Ozero Aynskoye",
            "Ozëra Golovkovskiye Plesa",
            "Ozero Veresnya",
            "Ozero Kuyvimali Lampi",
            "Ozero Bol’shoye",
            "Ozero Soroch’ye",
            "Ozero Yagiye",
            "Ozero Vuliyavr",
            "Ozero Tultyavr",
            "Ozero Suystamoyarvi",
            "Ozero Sudakovskoye",
            "Ozero Sredneye Shoba",
            "Ozero Solënoye",
            "Ozero Verkhneye Shirkoyarvi",
            "Ozero Severnoye Khattomozero",
            "Ozero Salon”yarvi",
            "Ozero Rovkul’skoye",
            "Ozero Rakhelampi",
            "Ozero Rigovarakskoye",
            "Ozero Rep”yavr",
            "Ozero Pyayveyavr",
            "Ozero Pyaozero",
            "Ozero Pushtos’-Yarvi",
            "Ozero Piz’ma-Yarvi",
            "Ozero Piyeni-Kontto-Yarvi",
            "Ozëra Pitkalampi",
            "Ozero Pil’nya",
            "Ozero Nekhvatova Pervoye",
            "Ozero Nyuk",
            "Ozero Nyud”yavr",
            "Ozero Noskuansel’kya",
    },

    rivers = {
            "Don",
            "Sochi",
            "Oka",
            "Seversky Donets",
            "Angara",
            "Ufa",
            "Onon",
            "Kyshtym",
            "Aldan",
            "Okhinka",
            "Irtysh",
            "Vitim",
            "Onega",
            "Luga",
            "Selenga",
            "Meleuz",
            "Yenisey",
            "Ingoda",
            "Kusa",
            "Малый Енисей",
            "Kyzyl-Khem",
            "Bol’shaya Avlandya",
            "Severnaya Dvina",
            "Lebyazh’ye",
            "Kovda",
            "Daneylamkhi",
            "Nëytayakha",
            "Большой Енисей",
            "Zheltura",
            "Dëlondë",
            "Uanga",
            "Amur",
            "Vyg",
            "Seng-Yakha",
            "Pol’noy Voronezh",
            "Pechenga",
            "Novosëlka",
            "Instruch",
            "Angrapa",
            "Meshekhi",
            "Ngarka-Tidngedayakha",
            "Suifen He",
            "Khima Tret’ya",
            "Bol’shoy Koltomoy",
            "Bol’shoy Veni",
            "Omrel’kay",
            "Bol’shoy El’genchen",
            "Bol’shoy Khatyngnakh",
            "Bezdol’nyy",
            "Tal’navayam",
            "Vaga",
            "Skirvytė",
            "Netkhoy",
            "Krasnaya",
            "Kerigo",
            "Alakhunchay",
            "Bol’shaya Tegin’",
            "Beysuzhek Pravyy",
            "Khulkhulau",
            "Goryanka",
            "Ustyu-Ishkin",
            "Nelyakoyakha",
            "Nyagyn’yugan",
            "Karkas’ya",
            "Margaritovka",
            "Chul’byu",
            "Zhitnitsa",
            "Vestovaya",
            "Yeyemyu",
            "Nelkandya",
            "Nyulkali Vtoraya",
            "Nyulkali Pervaya",
            "Nel’dtek Vtoroy",
            "Nel’dtek Pervyy",
            "Impoveyem",
            "Bol’shoy Garomay",
            "Bol’shaya Khadya",
            "Shubinskaya Rob’ya",
            "Chërnaya Rechka",
            "Maynalanyoki",
            "Malyy Ertil’",
            "Bol’shaya Smedva",
            "Bol’shaya Koz’ma",
            "Dal’nyaya",
            "Sobole-Yaga",
            "Ngynesëyakha",
            "Ngarkakhorteyakha",
            "Khal’mer’yu",
            "Bol’shaya Osipova",
            "Makarova",
            "Yagdyn’ya",
            "El’gekyan",
            "Bol’shiye Burgali",
            "Bol’shoy Inim",
            "Bol’shaya Kuli",
            "Bol’shoy Biyak",
            "Olen’ya",
            "Vul’vyveyem",
            "Tygyin-Kail’npyn",
            "Apapel’gin",
    },

    islands = {
            "Novaya Zemlya",
            "Sakhalin",
            "Diomede Islands",
            "Ostrov Vil’kitskogo",
            "Iturup Island",
            "Kunashir Island",
            "Wrangel Island",
            "Ostrov Bol’shoy Tyuters",
            "Shikotan Island",
            "Kuril Islands",
            "Petropavlovskaya Krepost’",
            "Ostrov Artura",
            "Komandorskiye Ostrova",
            "Habomai Islands",
            "Ostrov Atlasova",
            "Ostrov Malyy Tyuters",
            "Arkhipelag Bol’shoy Fiskar",
            "Ostrov Zelenyy",
            "Ostrov Beringa",
            "Ostrov Bell",
            "Big Diomede Island",
            "Franz Josef Land",
            "Ostrov Shumshu",
            "Ostrov Simushir",
            "Ostrov Paramushir",
            "Ostrov Peschanyy",
            "Ostrov Gorodomlya",
            "Ostrov Gogland",
            "Ostrov Bol’shoy Berëzovyy",
            "Todo Shima",
            "Taraku-jima",
            "Suishō-tō",
            "Ostrov Shiashkotan",
            "Ostrov Chirpoy",
            "Ostrov Tyuleniy",
            "Ostrov Severnyy Berëzovyy",
            "Ostrov Kotlin",
            "Ostrov Nizhniy",
            "Ostrova Ptich’i",
            "Ostrov Rasshua",
            "Ostrov Matua",
            "Ostrov Mayak",
            "Ō Shima",
            "Kamo Shima",
            "Kabuto Jima",
            "Gome Shima",
            "Ostrov Malyy Aynov",
            "Ostrov Bol’shoy Aynov",
            "Ostrov La-Rons’yer",
            "Ostrov Erkogor",
            "Moemoshiri Tō",
            "Ko Shima",
            "Kabu Shima",
            "Ostrov Ekarma",
            "Ostrova Chërnyye Brat’ya",
            "Solovki",
            "Ostrov Shënau",
            "Ostrova Rezanovy Ludy",
            "Ostrov Oktyabr’skoy Revolyutsii",
            "Ostrov Malyy Kuz’min",
            "Ostrova Iokan’gskiye",
            "Ostrov Ptichiy",
            "Yuri-tō",
            "Odoke Tō",
            "Ostrov Kharimkotan",
            "Ostrov Baydukova",
            "Kapitsa Island",
            "Ostrov Zhizhginskiy",
            "Ostrov Zapadnyy Berëzovyy",
            "Ostrov Rifovyy",
            "Ostrov Moshchnyy",
            "Ostrov Mayachnyy",
            "Ostrov Igrivyy",
            "Ostrov Golomyannyy",
            "Ostrov Chernetskiy",
            "Ostrov Bol’shaya Muksalma",
            "Ostrov Kolchaka",
            "Ostrova Ushishir",
            "Ostrov Raykoke",
            "Ostrov Onekotan",
            "New Siberian Islands",
            "Ostrov Moneron",
            "Ostrov Makanrushi",
            "Ostrov Ketoy",
            "Ostrov Faddeyevskiy",
            "Ostrov Chirinkotan",
            "Ostrov Broutona",
            "Ostrov Bol’shoy Lyakhovskiy",
            "Ostrov Ariy Kamen’",
            "Ostrov Antsiferova",
            "Ostrov Vysotskiy",
            "Ostrov Viktoriya",
            "Ostrova Ukhkontsy",
            "Ostrov Tuppuran-Saari",
            "Ostrov Syarkkyaluoto",
            "Ostrov Sosnovtsy",
            "Ostrov Sel’kyamar’yansari",
            "Ostrov Ryashkov",
            "Ostrov Rudol’fa",
            "Ostrov Raypatsari",
    },

    viewpoints = {
            "Mount Elbrus viewpoint",
            "Sparrow Hills viewpoint Moscow",
    },

    counties = {
        {
            name = "Adygeya",
            municipalities = {
                {
                    name = "Maykop Republican",
                    primary_city = "Maykop",
                    cities = { "Maykop" },
                },
            },
        },
        {
            name = "Altay",
            municipalities = {
                {
                    name = "Gorno-Altaysk",
                    primary_city = "Gorno-Altaysk",
                    cities = { "Gorno-Altaysk" },
                },
            },
        },
        {
            name = "Altayskiy Kray",
            municipalities = {
                {
                    name = "Barnaul",
                    primary_city = "Barnaul",
                    cities = { "Barnaul" },
                },
            },
        },
        {
            name = "Amur Oblast",
            municipalities = {
                {
                    name = "Amur Oblast",
                    primary_city = "Blagoveshchensk",
                    cities = { "Blagoveshchensk", "Belogorsk", "Svobodnyy" },
                },
            },
        },
        {
            name = "Arkhangelsk Oblast",
            municipalities = {
                {
                    name = "Primorskiy",
                    primary_city = "Arkhangel’sk",
                    cities = { "Arkhangel’sk" },
                },
            },
        },
        {
            name = "Astrakhan Oblast",
            municipalities = {
                {
                    name = "Astrakhan’",
                    primary_city = "Astrakhan",
                    cities = { "Astrakhan" },
                },
            },
        },
        {
            name = "Bashkortostan",
            municipalities = {
                {
                    name = "Bashkortostan",
                    primary_city = "Ufa",
                    cities = { "Ufa", "Sterlitamak", "Salavat", "Neftekamsk", "Oktyabrsky", "Beloretsk", "Ishimbay", "Tuymazy" },
                },
            },
        },
        {
            name = "Belgorod Oblast",
            municipalities = {
                {
                    name = "Belgorodskiy",
                    primary_city = "Belgorod",
                    cities = { "Belgorod" },
                },
            },
        },
        {
            name = "Bryansk Oblast",
            municipalities = {
                {
                    name = "Bryanskiy",
                    primary_city = "Bryansk",
                    cities = { "Bryansk" },
                },
            },
        },
        {
            name = "Buryatiya",
            municipalities = {
                {
                    name = "Ivolginskiy",
                    primary_city = "Ulan-Ude",
                    cities = { "Ulan-Ude" },
                },
            },
        },
        {
            name = "Chechenskaya Respublika",
            municipalities = {
                {
                    name = "Grozny",
                    primary_city = "Grozny",
                    cities = { "Grozny" },
                },
            },
        },
        {
            name = "Chelyabinsk Oblast",
            municipalities = {
                {
                    name = "Chelyabinskiy Gorodskoy",
                    primary_city = "Chelyabinsk",
                    cities = { "Chelyabinsk" },
                },
                {
                    name = "Magnitogorskiy Gorodskoy",
                    primary_city = "Magnitogorsk",
                    cities = { "Magnitogorsk" },
                },
            },
        },
        {
            name = "Chukotskiy Avtonomnyy Okrug",
            municipalities = {},
        },
        {
            name = "Chuvashskaya Respublika",
            municipalities = {
                {
                    name = "Cheboksarskiy",
                    primary_city = "Cheboksary",
                    cities = { "Cheboksary" },
                },
            },
        },
        {
            name = "Dagestan",
            municipalities = {
                {
                    name = "Gorod Kaspiysk",
                    primary_city = "Kaspiysk",
                    cities = { "Kaspiysk" },
                },
            },
        },
        {
            name = "Ingushetiya",
            municipalities = {
                {
                    name = "Sunzhensky",
                    primary_city = "Sunzha",
                    cities = { "Sunzha" },
                },
            },
        },
        {
            name = "Irkutsk Oblast",
            municipalities = {
                {
                    name = "Bratsk",
                    primary_city = "Bratsk",
                    cities = { "Bratsk" },
                },
                {
                    name = "Irkutskiy",
                    primary_city = "Irkutsk",
                    cities = { "Irkutsk" },
                },
            },
        },
        {
            name = "Ivanovo Oblast",
            municipalities = {
                {
                    name = "Ivanovo",
                    primary_city = "Ivanovo",
                    cities = { "Ivanovo" },
                },
            },
        },
        {
            name = "Jewish Autonomous Oblast",
            municipalities = {
                {
                    name = "Jewish Autonomous Oblast",
                    primary_city = "Birobidzhan",
                    cities = { "Birobidzhan" },
                },
            },
        },
        {
            name = "Kabardino-Balkarskaya Respublika",
            municipalities = {
                {
                    name = "Nalchik",
                    primary_city = "Nalchik",
                    cities = { "Nalchik" },
                },
            },
        },
        {
            name = "Kaliningrad Oblast",
            municipalities = {
                {
                    name = "Kaliningradskiy Gorodskoy",
                    primary_city = "Kaliningrad",
                    cities = { "Kaliningrad" },
                },
            },
        },
        {
            name = "Kalmykiya",
            municipalities = {
                {
                    name = "Kalmykiya",
                    primary_city = "Elista",
                    cities = { "Elista" },
                },
            },
        },
        {
            name = "Kaluga Oblast",
            municipalities = {
                {
                    name = "Kaluga Oblast",
                    primary_city = "Kaluga",
                    cities = { "Kaluga", "Obninsk" },
                },
            },
        },
        {
            name = "Kamchatka Krai",
            municipalities = {
                {
                    name = "Kamchatka Krai",
                    primary_city = "Petropavlovsk-Kamchatsky",
                    cities = { "Petropavlovsk-Kamchatsky" },
                },
            },
        },
        {
            name = "Karachayevo-Cherkesiya",
            municipalities = {
                {
                    name = "Karachayevo-Cherkesiya",
                    primary_city = "Cherkessk",
                    cities = { "Cherkessk" },
                },
            },
        },
        {
            name = "Kareliya",
            municipalities = {
                {
                    name = "Kareliya",
                    primary_city = "Petrozavodsk",
                    cities = { "Petrozavodsk" },
                },
            },
        },
        {
            name = "Kemerovo Oblast",
            municipalities = {
                {
                    name = "Kemerovo Oblast",
                    primary_city = "Kemerovo",
                    cities = { "Kemerovo", "Novokuznetsk", "Prokop’yevsk", "Leninsk-Kuznetsky", "Kiselëvsk", "Mezhdurechensk", "Kisilevsk", "Anzhero-Sudzhensk" },
                },
            },
        },
        {
            name = "Khabarovskiy Kray",
            municipalities = {
                {
                    name = "Khabarovskiy",
                    primary_city = "Khabarovsk",
                    cities = { "Khabarovsk" },
                },
            },
        },
        {
            name = "Khakasiya",
            municipalities = {
                {
                    name = "Khakasiya",
                    primary_city = "Abakan",
                    cities = { "Abakan", "Chernogorsk" },
                },
            },
        },
        {
            name = "Khanty-Mansiyskiy Avtonomnyy Okrug-Yugra",
            municipalities = {
                {
                    name = "Khanty-Mansiyskiy Avtonomnyy Okrug-Yugra",
                    primary_city = "Surgut",
                    cities = { "Surgut", "Nizhnevartovsk", "Nefteyugansk", "Khanty-Mansiysk", "Kogalym", "Nyagan" },
                },
            },
        },
        {
            name = "Kirov Oblast",
            municipalities = {
                {
                    name = "Kirovo-Chepetskiy",
                    primary_city = "Kirov",
                    cities = { "Kirov" },
                },
            },
        },
        {
            name = "Komi",
            municipalities = {
                {
                    name = "Syktyvdinskiy",
                    primary_city = "Syktyvkar",
                    cities = { "Syktyvkar" },
                },
            },
        },
        {
            name = "Kostroma Oblast",
            municipalities = {
                {
                    name = "Kostromskoy",
                    primary_city = "Kostroma",
                    cities = { "Kostroma" },
                },
            },
        },
        {
            name = "Krasnodarskiy Kray",
            municipalities = {
                {
                    name = "Sochi City",
                    primary_city = "Sochi",
                    cities = { "Sochi" },
                },
                {
                    name = "Tuapsinskiy",
                    primary_city = "Tuapse",
                    cities = { "Tuapse" },
                },
            },
        },
        {
            name = "Krasnoyarskiy Kray",
            municipalities = {
                {
                    name = "Krasnoyarskiy Kray",
                    primary_city = "Krasnoyarsk",
                    cities = { "Krasnoyarsk", "Norilsk", "Achinsk", "Kansk", "Zheleznogorsk", "Minusinsk", "Zelenogorsk", "Lesosibirsk" },
                },
            },
        },
        {
            name = "Kurgan Oblast",
            municipalities = {
                {
                    name = "Kurgan Oblast",
                    primary_city = "Kurgan",
                    cities = { "Kurgan", "Shadrinsk" },
                },
            },
        },
        {
            name = "Kursk Oblast",
            municipalities = {
                {
                    name = "Kursk Oblast",
                    primary_city = "Kursk",
                    cities = { "Kursk", "Zheleznogorsk" },
                },
            },
        },
        {
            name = "Leningrad Oblast",
            municipalities = {
                {
                    name = "Gatchinskiy",
                    primary_city = "Gatchina",
                    cities = { "Gatchina" },
                },
            },
        },
        {
            name = "Lipetsk Oblast",
            municipalities = {
                {
                    name = "Lipetsk Oblast",
                    primary_city = "Lipetsk",
                    cities = { "Lipetsk", "Yelets" },
                },
            },
        },
        {
            name = "Magadan Oblast",
            municipalities = {
                {
                    name = "Magadan Oblast",
                    primary_city = "Magadan",
                    cities = { "Magadan" },
                },
            },
        },
        {
            name = "Mariy-El",
            municipalities = {
                {
                    name = "Mariy-El",
                    primary_city = "Yoshkar-Ola",
                    cities = { "Yoshkar-Ola", "Volzhsk" },
                },
            },
        },
        {
            name = "Mordoviya",
            municipalities = {
                {
                    name = "Mordoviya",
                    primary_city = "Saransk",
                    cities = { "Saransk" },
                },
            },
        },
        {
            name = "Moscow",
            municipalities = {
                {
                    name = "Eastern Administrative",
                    primary_city = "Ivanovskoye",
                    cities = { "Ivanovskoye", "Veshnyaki", "Bogorodskoye", "Novogireyevo" },
                },
                {
                    name = "Severnyy Administrativnyy",
                    primary_city = "Vostochnoe Degunino",
                    cities = { "Vostochnoe Degunino" },
                },
                {
                    name = "Severo-Vostochnyy Administrativnyy",
                    primary_city = "Lianozovo",
                    cities = { "Lianozovo" },
                },
                {
                    name = "Yugo-Zapadnyy Administrativnyy",
                    primary_city = "Tyoply Stan",
                    cities = { "Tyoply Stan", "Cherëmushki", "Obruchevo" },
                },
                {
                    name = "Yuzhnyy Administrativnyy",
                    primary_city = "Zyablikovo",
                    cities = { "Zyablikovo", "Orekhovo-Borisovo Severnoye", "Brateyevo", "Nagornyy" },
                },
            },
        },
        {
            name = "Moscow Oblast",
            municipalities = {
                {
                    name = "Balashikha",
                    primary_city = "Zheleznodorozhnyy",
                    cities = { "Zheleznodorozhnyy" },
                },
                {
                    name = "Chekhov",
                    primary_city = "Chekhov",
                    cities = { "Chekhov" },
                },
                {
                    name = "Domodedovo",
                    primary_city = "Domodedovo",
                    cities = { "Domodedovo" },
                },
                {
                    name = "Khimki",
                    primary_city = "Khimki",
                    cities = { "Khimki" },
                },
                {
                    name = "Korolyov",
                    primary_city = "Korolev",
                    cities = { "Korolev" },
                },
                {
                    name = "Leninskiy Gorodskoy",
                    primary_city = "Vidnoye",
                    cities = { "Vidnoye" },
                },
                {
                    name = "Naro-Fominskiy Gorodskoy",
                    primary_city = "Naro-Fominsk",
                    cities = { "Naro-Fominsk" },
                },
                {
                    name = "Podolsk",
                    primary_city = "Podolsk",
                    cities = { "Podolsk" },
                },
                {
                    name = "Ramenskiy Gorodskoy",
                    primary_city = "Ramenskoye",
                    cities = { "Ramenskoye" },
                },
            },
        },
        {
            name = "Murmansk Oblast",
            municipalities = {
                {
                    name = "Murmansk Oblast",
                    primary_city = "Murmansk",
                    cities = { "Murmansk", "Apatity", "Severomorsk" },
                },
            },
        },
        {
            name = "Nenetskiy Avtonomnyy Okrug",
            municipalities = {},
        },
        {
            name = "Nizhny Novgorod Oblast",
            municipalities = {
                {
                    name = "Balakhninskiy",
                    primary_city = "Novaya Balakhna",
                    cities = { "Novaya Balakhna" },
                },
                {
                    name = "Bor",
                    primary_city = "Bor",
                    cities = { "Bor" },
                },
                {
                    name = "Kstovskiy",
                    primary_city = "Kstovo",
                    cities = { "Kstovo" },
                },
                {
                    name = "Pavlovskiy",
                    primary_city = "Pavlovo",
                    cities = { "Pavlovo" },
                },
            },
        },
        {
            name = "North Ossetia",
            municipalities = {
                {
                    name = "North Ossetia",
                    primary_city = "Vladikavkaz",
                    cities = { "Vladikavkaz" },
                },
            },
        },
        {
            name = "Novgorod Oblast",
            municipalities = {
                {
                    name = "Novgorod Oblast",
                    primary_city = "Velikiy Novgorod",
                    cities = { "Velikiy Novgorod", "Borovichi" },
                },
            },
        },
        {
            name = "Novosibirsk Oblast",
            municipalities = {
                {
                    name = "Novosibirskiy",
                    primary_city = "Novosibirsk",
                    cities = { "Novosibirsk" },
                },
            },
        },
        {
            name = "Omsk Oblast",
            municipalities = {
                {
                    name = "Omsk Oblast",
                    primary_city = "Omsk",
                    cities = { "Omsk" },
                },
            },
        },
        {
            name = "Orenburg Oblast",
            municipalities = {
                {
                    name = "Orenburg Oblast",
                    primary_city = "Orenburg",
                    cities = { "Orenburg", "Orsk", "Novotroitsk", "Buzuluk", "Krasnaya Glinka", "Buguruslan" },
                },
            },
        },
        {
            name = "Oryol Oblast",
            municipalities = {
                {
                    name = "Oryol Oblast",
                    primary_city = "Orël",
                    cities = { "Orël" },
                },
            },
        },
        {
            name = "Penza Oblast",
            municipalities = {
                {
                    name = "Kuznetskiy",
                    primary_city = "Kuznetsk",
                    cities = { "Kuznetsk", "Zarechnyy" },
                },
            },
        },
        {
            name = "Perm Krai",
            municipalities = {
                {
                    name = "Perm Krai",
                    primary_city = "Perm",
                    cities = { "Perm", "Berezniki", "Solikamsk", "Chaykovskiy", "Lys’va", "Kungur", "Krasnokamsk", "Chusovoy" },
                },
            },
        },
        {
            name = "Primorskiy Kray",
            municipalities = {
                {
                    name = "Primorskiy Kray",
                    primary_city = "Vladivostok",
                    cities = { "Vladivostok", "Ussuriysk", "Nakhodka", "Artëm", "Arsen’yev" },
                },
            },
        },
        {
            name = "Pskov Oblast",
            municipalities = {
                {
                    name = "Pskov Oblast",
                    primary_city = "Pskov",
                    cities = { "Pskov", "Velikiye Luki" },
                },
            },
        },
        {
            name = "Rostov Oblast",
            municipalities = {
                {
                    name = "Rostov Oblast",
                    primary_city = "Rostov-on-Don",
                    cities = { "Rostov-on-Don", "Taganrog", "Shakhty", "Volgodonsk", "Novocherkassk", "Bataysk", "Novoshakhtinsk", "Azov" },
                },
            },
        },
        {
            name = "Ryazan Oblast",
            municipalities = {
                {
                    name = "Ryazan Oblast",
                    primary_city = "Ryazan’",
                    cities = { "Ryazan’" },
                },
            },
        },
        {
            name = "Saint Petersburg",
            municipalities = {
                {
                    name = "Admiralteysky",
                    primary_city = "Admiralteisky",
                    cities = { "Admiralteisky" },
                },
                {
                    name = "Frunzenskiy",
                    primary_city = "Kupchino",
                    cities = { "Kupchino" },
                },
                {
                    name = "Kalininskiy",
                    primary_city = "Grazhdanka",
                    cities = { "Grazhdanka" },
                },
                {
                    name = "Kirovskiy",
                    primary_city = "Dachnoye",
                    cities = { "Dachnoye" },
                },
                {
                    name = "Pushkinskiy",
                    primary_city = "Pushkin",
                    cities = { "Pushkin" },
                },
            },
        },
        {
            name = "Sakha",
            municipalities = {
                {
                    name = "Yakutsk",
                    primary_city = "Yakutsk",
                    cities = { "Yakutsk" },
                },
            },
        },
        {
            name = "Sakhalin Oblast",
            municipalities = {
                {
                    name = "Sakhalin Oblast",
                    primary_city = "Yuzhno-Sakhalinsk",
                    cities = { "Yuzhno-Sakhalinsk" },
                },
            },
        },
        {
            name = "Samara Oblast",
            municipalities = {
                {
                    name = "Samara Oblast",
                    primary_city = "Samara",
                    cities = { "Samara", "Tolyatti", "Syzran", "Novokuybyshevsk", "Chapayevsk", "Zhigulëvsk", "Otradnyy" },
                },
            },
        },
        {
            name = "Saratovskaya Oblast",
            municipalities = {
                {
                    name = "Saratovskiy",
                    primary_city = "Saratov",
                    cities = { "Saratov" },
                },
            },
        },
        {
            name = "Smolensk Oblast",
            municipalities = {
                {
                    name = "Smolensk Oblast",
                    primary_city = "Smolensk",
                    cities = { "Smolensk", "Roslavl’", "Vyaz’ma", "Yartsevo" },
                },
            },
        },
        {
            name = "Stavropol Kray",
            municipalities = {
                {
                    name = "Stavropol Kray",
                    primary_city = "Stavropol",
                    cities = { "Stavropol", "Pyatigorsk", "Nevinnomyssk", "Kislovodsk", "Yessentuki", "Mineralnye Vody", "Georgiyevsk", "Budyonnovsk" },
                },
            },
        },
        {
            name = "Sverdlovsk Oblast",
            municipalities = {
                {
                    name = "Sverdlovsk Oblast",
                    primary_city = "Yekaterinburg",
                    cities = { "Yekaterinburg", "Nizhny Tagil", "Kamensk-Ural’skiy", "Pervouralsk", "Serov", "Novoural’sk", "Asbest", "Polevskoy" },
                },
            },
        },
        {
            name = "Tambov Oblast",
            municipalities = {
                {
                    name = "Tambov Oblast",
                    primary_city = "Tambov",
                    cities = { "Tambov", "Michurinsk" },
                },
            },
        },
        {
            name = "Tatarstan",
            municipalities = {
                {
                    name = "Kazan’",
                    primary_city = "Kazan",
                    cities = { "Kazan" },
                },
                {
                    name = "Tukayevskiy",
                    primary_city = "Naberezhnyye Chelny",
                    cities = { "Naberezhnyye Chelny" },
                },
            },
        },
        {
            name = "Tomsk Oblast",
            municipalities = {
                {
                    name = "Tomskiy",
                    primary_city = "Tomsk",
                    cities = { "Tomsk" },
                },
            },
        },
        {
            name = "Tula Oblast",
            municipalities = {
                {
                    name = "Tula Oblast",
                    primary_city = "Tula",
                    cities = { "Tula", "Novomoskovsk", "Aleksin", "Shchëkino", "Uzlovaya" },
                },
            },
        },
        {
            name = "Tver Oblast",
            municipalities = {
                {
                    name = "Tver Oblast",
                    primary_city = "Tver",
                    cities = { "Tver", "Rzhev", "Vyshniy Volochëk", "Kimry" },
                },
            },
        },
        {
            name = "Tyumen Oblast",
            municipalities = {
                {
                    name = "Tyumen Oblast",
                    primary_city = "Tyumen",
                    cities = { "Tyumen", "Tobolsk", "Ishim" },
                },
            },
        },
        {
            name = "Tyva",
            municipalities = {
                {
                    name = "Tyva",
                    primary_city = "Kyzyl",
                    cities = { "Kyzyl" },
                },
            },
        },
        {
            name = "Udmurtskaya Respublika",
            municipalities = {
                {
                    name = "Udmurtskaya Respublika",
                    primary_city = "Izhevsk",
                    cities = { "Izhevsk", "Glazov", "Sarapul", "Votkinsk" },
                },
            },
        },
        {
            name = "Ulyanovsk Oblast",
            municipalities = {
                {
                    name = "Ulyanovskiy",
                    primary_city = "Ulyanovsk",
                    cities = { "Ulyanovsk" },
                },
            },
        },
        {
            name = "Vladimirskaya Oblast",
            municipalities = {
                {
                    name = "Kovrovskiy",
                    primary_city = "Kovrov",
                    cities = { "Kovrov" },
                },
            },
        },
        {
            name = "Volgograd Oblast",
            municipalities = {
                {
                    name = "Volgograd Oblast",
                    primary_city = "Volgograd",
                    cities = { "Volgograd", "Volzhsky", "Kamyshin", "Mikhaylovka" },
                },
            },
        },
        {
            name = "Vologda Oblast",
            municipalities = {
                {
                    name = "Vologda Oblast",
                    primary_city = "Cherepovets",
                    cities = { "Cherepovets", "Vologda" },
                },
            },
        },
        {
            name = "Voronezh Oblast",
            municipalities = {
                {
                    name = "Voronezh Oblast",
                    primary_city = "Voronezh",
                    cities = { "Voronezh", "Borisoglebsk", "Rossosh’", "Liski" },
                },
            },
        },
        {
            name = "Yamalo-Nenetskiy Avtonomnyy Okrug",
            municipalities = {
                {
                    name = "Yamalo-Nenetskiy Avtonomnyy Okrug",
                    primary_city = "Noyabrsk",
                    cities = { "Noyabrsk", "Novyy Urengoy" },
                },
            },
        },
        {
            name = "Yaroslavl Oblast",
            municipalities = {
                {
                    name = "Yaroslavl Oblast",
                    primary_city = "Yaroslavl",
                    cities = { "Yaroslavl", "Rybinsk" },
                },
            },
        },
        {
            name = "Zabaykalsky Krai",
            municipalities = {
                {
                    name = "Zabaykalsky Krai",
                    primary_city = "Chita",
                    cities = { "Chita", "Krasnokamensk" },
                },
            },
        },
    },

}
